export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';


export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SET_SIGNUP_REDIRECT_PATH = 'SET_SIGNUP_REDIRECT_PATH';

export const SEARCH_GET_UNIQUE_CATEGORY = 'SEARCH_GET_UNIQUE_CATEGORY';
export const SEARCH_GET_PRODUCTS_CATEGORY_SUBCATEGORY ='SEARCH_GET_PRODUCTS_CATEGORY_SUBCATEGORY';
export const SEARCH_GET_SUB_CATEGORY = 'SEARCH_GET_SUB_CATEGORY';
export const SEARCH_GET_UNIQUE_CATEGORY_FAIL = 'SEARCH_GET_UNIQUE_CATEGORY_FAIL';
export const EARCH_GET_PRODUCTS_CATEGORY_SUBCATEGORY_FAIL = 'EARCH_GET_PRODUCTS_CATEGORY_SUBCATEGORY_FAIL';
export const SET_SEARCH_REDIRECT_PATH  = 'SET_SEARCH_REDIRECT_PATH';
export const SEARCH_HAVE_PRODUCT_LIST= 'SEARCH_HAVE_PRODUCT_LIST';

export const PRODUCT_SETSELECTEDPRODUCT = 'PRODUCT_SETSELECTEDPRODUCT';
export const SET_PRODUCT_REDIRECT_PATH  = 'SET_PRODUCT_REDIRECT_PATH';
export const SET_COMPARED_PRODUCT = 'SET_COMPARED_PRODUCT';
export const SET_COMPARE_CLICKED = 'SET_COMPARE_CLICKED';
export const SET_REDIRECT_TO_COMPARE = 'SET_REDIRECT_TO_COMPARE';
